# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information_about_the_rules_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label_exp = QtWidgets.QLabel(Form)
        self.label_exp.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.label_exp.setObjectName("label_exp")
        self.label_name_inf = QtWidgets.QLabel(Form)
        self.label_name_inf.setGeometry(QtCore.QRect(150, 10, 241, 16))
        self.label_name_inf.setObjectName("label_name_inf")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(10, 10, 55, 16))
        self.label_name.setObjectName("label_name")
        self.label_exp_inf = QtWidgets.QLabel(Form)
        self.label_exp_inf.setGeometry(QtCore.QRect(150, 30, 241, 16))
        self.label_exp_inf.setObjectName("label_exp_inf")
        self.label_virtual_coins_inf = QtWidgets.QLabel(Form)
        self.label_virtual_coins_inf.setGeometry(QtCore.QRect(150, 50, 241, 16))
        self.label_virtual_coins_inf.setObjectName("label_virtual_coins_inf")
        self.label_virtual_coins = QtWidgets.QLabel(Form)
        self.label_virtual_coins.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label_virtual_coins.setObjectName("label_virtual_coins")
        self.label_described_inf = QtWidgets.QLabel(Form)
        self.label_described_inf.setGeometry(QtCore.QRect(150, 70, 241, 16))
        self.label_described_inf.setObjectName("label_described_inf")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 230, 401, 71))
        self.pushButton.setObjectName("pushButton")
        self.label_described = QtWidgets.QLabel(Form)
        self.label_described.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_described.setObjectName("label_described")
        self.label_violated = QtWidgets.QLabel(Form)
        self.label_violated.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_violated.setObjectName("label_violated")
        self.label_violated_inf = QtWidgets.QLabel(Form)
        self.label_violated_inf.setGeometry(QtCore.QRect(150, 90, 241, 16))
        self.label_violated_inf.setObjectName("label_violated_inf")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_exp.setText(_translate("Form", "Опыт:"))
        self.label_name_inf.setText(_translate("Form", "s"))
        self.label_name.setText(_translate("Form", "Имя:"))
        self.label_exp_inf.setText(_translate("Form", "s"))
        self.label_virtual_coins_inf.setText(_translate("Form", "s"))
        self.label_virtual_coins.setText(_translate("Form", "Виртуальные монеты"))
        self.label_described_inf.setText(_translate("Form", "s"))
        self.pushButton.setText(_translate("Form", "Назад"))
        self.label_described.setText(_translate("Form", "Описание:"))
        self.label_violated.setText(_translate("Form", "Нарушено:"))
        self.label_violated_inf.setText(_translate("Form", "s"))
