# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label_exp = QtWidgets.QLabel(Form)
        self.label_exp.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_exp.setObjectName("label_exp")
        self.label_name_inf = QtWidgets.QLabel(Form)
        self.label_name_inf.setGeometry(QtCore.QRect(150, 10, 241, 16))
        self.label_name_inf.setObjectName("label_name_inf")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_name.setObjectName("label_name")
        self.label_frequency_inf = QtWidgets.QLabel(Form)
        self.label_frequency_inf.setGeometry(QtCore.QRect(150, 30, 241, 16))
        self.label_frequency_inf.setObjectName("label_frequency_inf")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 230, 401, 71))
        self.pushButton.setObjectName("pushButton")
        self.label_frequency = QtWidgets.QLabel(Form)
        self.label_frequency.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_frequency.setObjectName("label_frequency")
        self.label_exp_inf = QtWidgets.QLabel(Form)
        self.label_exp_inf.setGeometry(QtCore.QRect(150, 50, 241, 16))
        self.label_exp_inf.setObjectName("label_exp_inf")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_exp.setText(_translate("Form", "Правил нарушено:"))
        self.label_name_inf.setText(_translate("Form", "s"))
        self.label_name.setText(_translate("Form", "просроченных задач:"))
        self.label_frequency_inf.setText(_translate("Form", "s"))
        self.pushButton.setText(_translate("Form", "Назад"))
        self.label_frequency.setText(_translate("Form", "решенных задач:"))
        self.label_exp_inf.setText(_translate("Form", "s"))
